- name: Wait for Nexus to be ready
  wait_for:
    host: "localhost"
    port: 8082
    timeout: 300

- name: Get Nexus admin password
  command: docker exec nexus cat /nexus-data/admin.password
  register: nexus_admin_password
  changed_when: false

- name: Get list of default repositories
  uri:
    url: "http://localhost:8082/service/rest/v1/repositories"
    method: GET
    user: "admin"
    password: "{{ nexus_admin_password.stdout }}"
    force_basic_auth: yes
    return_content: yes
  register: nexus_repos

- name: Delete default repositories
  uri:
    url: "http://localhost:8082/service/rest/v1/repositories/{{ item.name }}"
    method: DELETE
    user: "admin"
    password: "{{ nexus_admin_password.stdout }}"
    force_basic_auth: yes
    status_code: [ 204, 404 ]
  loop: "{{ nexus_repos.json }}"

- name: Create Nexus repositories
  uri:
    url: "http://localhost:8082/service/rest/v1/repositories/{{ item.type }}"
    method: POST
    user: "admin"
    password: "{{ nexus_admin_password.stdout }}"
    body_format: json
    body: "{{ lookup('file', item.file) }}"
  loop:
    - { type: 'docker/hosted', file: 'files/docker-hosted.json' }
    - { type: 'docker/proxy', file: 'files/docker-proxy.json' }
    - { type: 'go/proxy', file: 'files/go-proxy.json' }
  register: result
  failed_when: result.status != 201 and result.status != 409