stages:
  - build-and-push

variables:
  DOCKER_IMAGE: "my-go-app"

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_REGISTRY_USER" --password-stdin
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_TAG"
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_TAG" .
  only:
    - tags
  tags:
    - docker
