stages:
  - build-and-push

variables:
  DOCKER_IMAGE: "my-go-app"

build-and-push:
  stage: build-and-push
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--insecure-registry=nexus:"]
  script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" --username "$DOCKER_REGISTRY_USER" --password-stdin
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_TAG"
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_TAG" .
  only:
    - tags
  tags:
    - docker
